# Generated by Django 5.2.5 on 2025-08-14 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_company_name_user_company_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='professional_documents/cvs/')),
                ('aviation_licenses', models.FileField(blank=True, null=True, upload_to='professional_documents/licenses/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professional Document',
                'verbose_name_plural': 'Professional Documents',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('aviation_specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professional Experience',
                'verbose_name_plural': 'Professional Experiences',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('professional_bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professional Personal Info',
                'verbose_name_plural': 'Professional Personal Info',
            },
        ),
        migrations.CreateModel(
            name='RecruiterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_documents', models.FileField(blank=True, null=True, upload_to='recruiter_documents/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter Document',
                'verbose_name_plural': 'Recruiter Documents',
            },
        ),
    ]
