# Generated by Django 5.2.5 on 2025-08-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_professionaldocument_professionalexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalpersonalinfo',
            name='location',
            field=models.CharField(blank=True, help_text='General location description', max_length=255, null=True),
        ),
    ]
