# Generated by Django 5.2.5 on 2025-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_professionalpersonalinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalpersonalinfo',
            name='availability',
            field=models.CharField(blank=True, choices=[('immediately', 'Immediately available'), ('within_1_month', 'Available within 1 month'), ('within_3_months', 'Available within 3 months'), ('contract_bound', 'Contract-bound'), ('other', 'Other')], help_text='Current availability status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='professionalpersonalinfo',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('french', 'French'), ('german', 'German'), ('spanish', 'Spanish'), ('chinese', 'Chinese'), ('arabic', 'Arabic'), ('russian', 'Russian'), ('portuguese', 'Portuguese'), ('swahili', 'Swahili'), ('japanese', 'Japanese'), ('hindi', 'Hindi'), ('italian', 'Italian')], help_text='Preferred language', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professionalpersonalinfo',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='professionalpersonalinfo',
            name='preferred_work_regions',
            field=models.CharField(blank=True, help_text='Preferred regions for work opportunities (comma-separated)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionalpersonalinfo',
            name='willing_to_relocate',
            field=models.BooleanField(default=False, help_text='Whether the professional is willing to relocate for work'),
        ),
    ]
