# Generated by Django 5.2.5 on 2025-09-02 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_professionalpersonalinfo_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviation_category', models.CharField(choices=[('pilot', 'Pilot'), ('flight_attendant', 'Flight Attendant'), ('engineer', 'Engineer'), ('technician', 'Technician'), ('atc', 'Air Traffic Controller'), ('ground_ops', 'Ground Operations'), ('dispatcher', 'Dispatcher'), ('other', 'Other')], max_length=50, verbose_name='Aviation Category')),
                ('title', models.CharField(help_text='E.g., Captain, First Officer, A&P Technician, etc.', max_length=100, verbose_name='Rank/Title')),
                ('aircraft_type_experience', models.CharField(blank=True, help_text='Aircraft types separated by commas', max_length=255, null=True)),
                ('icao_type_ratings', models.CharField(blank=True, help_text='ICAO Type Ratings separated by commas', max_length=255, null=True)),
                ('icao_ratings_expiry', models.DateField(blank=True, help_text='Expiry date for ICAO Type Ratings', null=True)),
                ('regulatory_body', models.CharField(blank=True, choices=[('kcaa', 'KCAA'), ('faa', 'FAA'), ('easa', 'EASA'), ('icao', 'ICAO'), ('other', 'Other')], help_text='Regulatory body registered with', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professional Role',
                'verbose_name_plural': 'Professional Roles',
            },
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_education_level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=20, verbose_name='Highest Education Level')),
                ('course_of_study', models.CharField(max_length=200, verbose_name='Course of Study')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution')),
                ('expected_graduation_year', models.CharField(max_length=10, verbose_name='Expected Graduation Year')),
                ('aviation_certifications', models.TextField(blank=True, help_text='Aviation-specific certifications separated by commas', null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='GPA Attained')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
            },
        ),
    ]
