# Generated by Django 5.2.5 on 2025-09-03 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_professionalroles_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldocument',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='professional_documents/passports/'),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='reference_letters',
            field=models.FileField(blank=True, null=True, upload_to='professional_documents/references/'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='certificate_upload',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificate Upload'),
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('start_date', models.DateField(help_text='Employment start date')),
                ('end_date', models.DateField(blank=True, help_text='Employment end date (leave blank if current)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Check if this is your current employment')),
                ('responsibilities', models.TextField()),
                ('reason_leaving', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LicensesRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(help_text='Multiple license types can be selected (comma-separated)', max_length=255, verbose_name='License Type')),
                ('issue_authority', models.CharField(max_length=100, verbose_name='Issue Authority')),
                ('license_number', models.CharField(max_length=100, verbose_name='License Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('license_rating', models.CharField(help_text='Multiple ratings can be selected (comma-separated)', max_length=255, verbose_name='License Rating')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('license_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('pending', 'Pending'), ('revoked', 'Revoked')], default='active', max_length=50, verbose_name='Current Status')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='Renewal Date')),
                ('license_upload', models.FileField(blank=True, null=True, upload_to='licenses/', verbose_name='License Upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
    ]
