# Generated by Django 5.2.5 on 2025-09-03 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_professionaldocument_passport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_address', models.CharField(max_length=300)),
                ('organization_email', models.EmailField(max_length=255)),
                ('organization_phone', models.CharField(max_length=15)),
                ('organization_website', models.URLField()),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('organization_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_type', models.CharField(choices=[('airline', 'Airline'), ('mro', 'MRO'), ('training institute', 'Training Institute'), ('airfield operators', 'Airfield Operators'), ('advocacy groups', 'Advocacy Groups')], default='airline', max_length=50, verbose_name='Organization Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Brief description about the user', null=True)),
                ('tagline', models.CharField(blank=True, help_text='A short professional tagline', max_length=255, null=True)),
                ('profile_visibility', models.BooleanField(default=True, help_text='Whether the profile is visible to others')),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('social_linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=255, null=True)),
                ('social_twitter', models.URLField(blank=True, help_text='Twitter profile URL', max_length=255, null=True)),
                ('social_github', models.URLField(blank=True, help_text='GitHub profile URL', max_length=255, null=True)),
                ('social_facebook', models.URLField(blank=True, help_text='Facebook profile URL', max_length=255, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills', null=True)),
                ('interests', models.TextField(blank=True, help_text='Comma-separated list of interests', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
