# Generated by Django 5.2.5 on 2025-09-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_organizationprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='organization_address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='organization_email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='organization_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='organization_website',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
