# Generated by Django 5.2.5 on 2025-09-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_company_name_remove_user_company_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProfessionalProfile',
        ),
        migrations.DeleteModel(
            name='RecruiterProfile',
        ),
    ]
