# Generated by Django 5.2.5 on 2025-09-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_uploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={},
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='professional_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='users.professionaldocument'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploaded_files/'),
        ),
    ]
