# Generated by Django 5.2.5 on 2025-09-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_uploadedfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('cv', 'Curriculum Vitae'), ('aviation_licenses', 'Aviation Licenses'), ('passport', 'Passport'), ('reference_letters', 'Reference Letters'), ('certificates', 'Certificates'), ('other', 'Other Documents')], default='other', max_length=50, verbose_name='Document Category'),
        ),
    ]
