# Generated by Django 5.2.5 on 2025-09-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_uploadedfile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('cv', 'Curriculum Vitae'), ('aviation_licenses', 'Aviation Licenses'), ('passport', 'Passport'), ('reference_letters', 'Reference Letters'), ('certificates', 'Certificates'), ('certificate_upload ', 'Certificate Upload'), ('other', 'Other Documents')], default='other', max_length=50, verbose_name='Document Category'),
        ),
    ]
