# Generated by Django 5.2.5 on 2025-09-16 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_uploadedfile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_resubmission', 'Needs Resubmission')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('aviation_licenses', 'Aviation Licenses'), ('passport', 'Passport'), ('reference_letters', 'Reference Letters'), ('certificate_upload ', 'Certificate Upload'), ('other', 'Other Documents')], default='other', max_length=50, verbose_name='Document Category'),
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_resubmission', 'Needs Resubmission')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='users.uploadedfile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('education_verified', models.BooleanField(default=False)),
                ('employment_verified', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('licenses_verified', models.BooleanField(default=False)),
                ('last_verification_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
