# Generated by Django 5.2.5 on 2025-09-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_uploadedfile_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterdocument',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter_logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_type',
            field=models.CharField(choices=[('airline', 'Airline'), ('mro', 'MRO'), ('training institute', 'Training Institute'), ('airfield operators', 'Airfield Operators'), ('advocacy groups', 'Advocacy Groups')], default='airline', max_length=50, verbose_name='Organization Type'),
        ),
        migrations.DeleteModel(
            name='OrganizationProfile',
        ),
    ]
