# Generated by Django 5.2.5 on 2025-09-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_recruiterdocument_company_logo_user_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization_type',
        ),
        migrations.AddField(
            model_name='user',
            name='company_type',
            field=models.CharField(choices=[('airline', 'Airline'), ('mro', 'MRO'), ('training institute', 'Training Institute'), ('airfield operators', 'Airfield Operators'), ('advocacy groups', 'Advocacy Groups')], default='airline', max_length=50, verbose_name='Company Type'),
        ),
    ]
