# Generated by Django 5.2.5 on 2025-09-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_uploadedfile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_type',
            field=models.CharField(choices=[('airline', 'Airline'), ('mro', 'MRO'), ('training institute', 'Training Institute'), ('airfield operators', 'Airfield Operators'), ('advocacy groups', 'Advocacy Groups'), ('ngos', 'NGOs'), ('government agencies', 'Government Agencies'), ('other', 'Other')], default='airline', max_length=50, verbose_name='Company Type'),
        ),
    ]
