# Generated by Django 5.2.5 on 2025-09-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_company_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensesratings',
            options={'verbose_name': 'License & Rating', 'verbose_name_plural': 'Licenses & Ratings'},
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='major_task_performed',
            field=models.CharField(blank=True, choices=[('Line maintenance on A320 fleet', 'Line maintenance on A320 fleet'), ('ATC Area Control for Nairobi FIR', 'ATC Area Control for Nairobi FIR'), ('Cabin Crew Safety and services on B787 long haul', 'Cabin Crew Safety and services on B787 long haul')], help_text='Major tasks performed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='nature_of_employer',
            field=models.CharField(blank=True, help_text='Select the nature of the employer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='supporting_documents',
            field=models.FileField(blank=True, help_text='Upload work references or employment letters (PDF, JPG)', null=True, upload_to='employment_references/'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='types_of_aircraft',
            field=models.CharField(blank=True, choices=[('B737-800, A320,Dash 8', 'B737-800, A320,Dash 8'), ('Q400, Embraer 190, Cessna 208', 'Q400, Embraer 190, Cessna 208')], help_text='Types of aircraft flown/maintained', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='types_of_mission',
            field=models.CharField(blank=True, choices=[('Domestic', 'Domestic'), ('International', 'International'), ('Long Haul', 'Long Haul'), ('Short Haul', 'Short Haul'), ('Cargo', 'Cargo'), ('Vip', 'Vip'), ('Humanitarian', 'Humanitarian'), ('Military', 'Military')], help_text='Scope of operations / type of missions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licensesratings',
            name='medical_certificate_class',
            field=models.CharField(blank=True, choices=[('class_1', 'Class 1 Medical (Pilots/ATC)'), ('class_2', 'Class 2 Medical (Private Pilots)'), ('lapl', 'LAPL Medical'), ('cabin_crew', 'Cabin Crew Medical'), ('ame', 'Aeromedical Examiner'), ('other', 'Other')], max_length=20, null=True, verbose_name='Medical Certificate Class'),
        ),
        migrations.AddField(
            model_name='licensesratings',
            name='medical_certificate_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Medical Certificate Expiry'),
        ),
        migrations.AddField(
            model_name='licensesratings',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('flagged', 'Flagged')], default='pending', max_length=20, verbose_name='Verification Status'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='aviation_certifications_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Certification Expiry Date'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='continuous_training_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Training Expiry Date'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='continuous_training_last_completed',
            field=models.DateField(blank=True, null=True, verbose_name='Last Training Completed'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='continuous_training_records',
            field=models.TextField(blank=True, help_text='Recurrent/mandatory training records', null=True),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='continuous_training_upload',
            field=models.FileField(blank=True, null=True, upload_to='continuous_training/', verbose_name='Training Records'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='country',
            field=models.CharField(default='kenya', max_length=100, verbose_name='Country of Institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualifications',
            name='professional_development_courses',
            field=models.TextField(blank=True, help_text='Short courses or professional development programs', null=True),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='professional_development_upload',
            field=models.FileField(blank=True, null=True, upload_to='professional_development/', verbose_name='Supporting Documents'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='workshops_seminars',
            field=models.TextField(blank=True, help_text='Workshops and seminars attended', null=True),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='workshops_upload',
            field=models.FileField(blank=True, null=True, upload_to='workshops/', verbose_name='Workshop Certificates'),
        ),
        migrations.AlterField(
            model_name='licensesratings',
            name='issue_authority',
            field=models.CharField(choices=[('kcaa', 'Kenya Civil Aviation Authority (KCAA)'), ('faa', 'Federal Aviation Administration (FAA – USA)'), ('easa', 'European Union Aviation Safety Agency (EASA – EU)'), ('uk_caa', 'Civil Aviation Authority (UK)'), ('dgca_india', 'DGCA India'), ('sacaa', 'South African CAA'), ('ncaa', 'Nigerian CAA'), ('tcaa', 'Tanzania CAA'), ('gcaa_uae', 'GCAA (UAE)'), ('caac', 'Civil Aviation Administration of China (CAAC)'), ('casa', 'Civil Aviation Safety Authority (Australia)'), ('tcca', 'Transport Canada Civil Aviation'), ('icao', 'ICAO-recognized Authority'), ('other', 'Other')], max_length=50, verbose_name='Issuing Authority'),
        ),
        migrations.AlterField(
            model_name='licensesratings',
            name='license_rating',
            field=models.CharField(choices=[('instrument', 'Instrument Rating (IR)'), ('night', 'Night Rating'), ('multi_engine', 'Multi-Engine Rating'), ('instructor', 'Instructor Rating'), ('type', 'Type Rating (B737, A320, ATR72, etc.)'), ('language', 'Language Proficiency (ICAO Level 4/5/6)'), ('atc', 'ATC Ratings (TWR, APP, ACC, Oceanic, Radar, Procedural)'), ('cabin_crew', 'Cabin Crew Ratings (SEP, DG, AVSEC, First Aid)'), ('dispatcher', 'Dispatcher Ratings (ETOPS, Long Haul, Route/Weather)'), ('drone', 'Drone/UAV Ratings (BVLOS, EVLOS, Payload)'), ('other', 'Other')], max_length=100, verbose_name='License Rating'),
        ),
        migrations.AlterField(
            model_name='licensesratings',
            name='license_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('pending', 'Pending Renewal'), ('revoked', 'Revoked')], default='active', max_length=20, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='licensesratings',
            name='license_type',
            field=models.CharField(choices=[('spl', 'Student Pilot Licence (SPL)'), ('ppl', 'Private Pilot Licence (PPL)'), ('cpl', 'Commercial Pilot Licence (CPL)'), ('mpl', 'Multi-Crew Pilot Licence (MPL)'), ('atpl', 'Airline Transport Pilot Licence (ATPL)'), ('fi', 'Flight Instructor Licence (FI/CFI)'), ('rpl', 'Remote Pilot Licence (RPL – UAV/Drone)'), ('ame', 'Aircraft Maintenance Engineer (AME – ICAO/FAA/EASA Part-66)'), ('faa_ap', 'FAA A&P (Airframe & Powerplant)'), ('easa_part_66', 'EASA Part-66 Categories (A, B1, B2, B3, C)'), ('atc_student', 'Student ATCO Licence'), ('atc_full', 'Full ATC Licence'), ('dispatcher', 'Flight Dispatcher Licence (ICAO Doc 7192)'), ('cabin_crew', 'Cabin Crew Licence/Attestation'), ('aero_station', 'Aeronautical Station Operator Licence'), ('meteo', 'Meteorologist Certification'), ('ame_examiner', 'Aeromedical Examiner Licence'), ('other', 'Other')], max_length=100, verbose_name='License Type'),
        ),
        migrations.AlterField(
            model_name='professionalroles',
            name='aviation_category',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('cabin_crew', 'Cabin Crew / Inflight'), ('atc', 'Air Traffic Services'), ('dispatcher', 'Flight Ops / Dispatch / OCC'), ('engineer', 'Maintenance & Engineering'), ('ground_ops', 'Airport & Ground Ops'), ('safety', 'Safety / Quality / Security')], max_length=50, verbose_name='Aviation Category'),
        ),
        migrations.AlterField(
            model_name='professionalroles',
            name='title',
            field=models.CharField(choices=[('student_pilot', 'Student Pilot / Cadet'), ('second_officer', 'Second Officer'), ('first_officer', 'First Officer (FO)'), ('senior_first_officer', 'Senior First Officer'), ('captain', 'Captain / Pilot-in-Command'), ('senior_captain', 'Senior Captain'), ('training_captain', 'Training Captain / Line Check Captain'), ('tri', 'Type Rating Instructor (TRI)'), ('tre', 'Type Rating Examiner (TRE) / DPE'), ('fleet_captain', 'Fleet Captain / Chief Pilot'), ('director_flight_ops', 'Director of Flight Operations'), ('trainee_cc', 'Trainee Cabin Crew'), ('cabin_crew', 'Cabin Crew / Flight Attendant'), ('senior_cabin_crew', 'Senior Cabin Crew'), ('purser', 'Purser / Lead Cabin Crew'), ('inflight_supervisor', 'Inflight Supervisor / Cabin Manager'), ('cc_instructor', 'Cabin Crew Instructor'), ('trainee_atc', 'ATC Trainee'), ('tower', 'Tower (TWR) Controller'), ('approach', 'Approach (APP) Controller'), ('area', 'Area / En-route (ACC) Controller'), ('oceanic', 'Oceanic Controller'), ('atc_supervisor', 'ATC Watch Supervisor / Unit Supervisor'), ('atc_instructor', 'ATC Instructor (OJTI) / Examiner'), ('unit_manager', 'Unit Manager / Chief ATCO'), ('trainee_dispatcher', 'Trainee Dispatcher / Flight Follower'), ('dispatcher', 'Flight Operations Officer / Dispatcher'), ('senior_dispatcher', 'Senior Dispatcher'), ('occ_controller', 'OCC Controller / Duty Manager'), ('manager_flight_ops', 'Manager, Flight Operations Control'), ('apprentice', 'Apprentice / Junior Technician'), ('technician', 'Aircraft Mechanic / Technician (Airframe/Powerplant/Avionics)'), ('licensed_ame', 'Licensed AME (Cat A, B1, B2, B3, C)'), ('lead_engineer', 'Lead / Certifying Engineer'), ('line_supervisor', 'Line Maintenance Supervisor'), ('base_supervisor', 'Base Maintenance Supervisor'), ('camo_engineer', 'Continuing Airworthiness Engineer / CAMO'), ('ars', 'Airworthiness Review Staff (ARS)'), ('maintenance_manager', 'Maintenance / Engineering Manager'), ('postholder', 'Part-145 / Part-M / Part-CAMO Postholder'), ('ramp_agent', 'Ramp Agent'), ('load_controller', 'Load Controller'), ('loadmaster', 'Loadmaster'), ('turnaround_coordinator', 'Turnaround Coordinator'), ('ground_ops_supervisor', 'Ground Ops Supervisor'), ('station_manager', 'Station Manager'), ('sms_officer', 'SMS Officer / Manager'), ('quality_auditor', 'Compliance Monitoring / Quality Auditor'), ('safety_investigator', 'Safety Investigator'), ('avsec', 'AVSEC Screener / Officer / Manager'), ('dgr_officer', 'DGR (Cat 6) Officer')], max_length=100, verbose_name='Rank/Title'),
        ),
        migrations.AlterField(
            model_name='qualifications',
            name='highest_education_level',
            field=models.CharField(choices=[('high_school', 'High_School'), ('primary', 'Primary'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=20, verbose_name='Highest Education Level'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('cv', 'Curriculum Vitae'), ('aviation_license', 'Aviation License'), ('passport', 'Passport'), ('reference_letter', 'Reference Letter'), ('certificate_upload', 'Certificate Upload'), ('other', 'Other')], default='other', max_length=50, verbose_name='Document Category'),
        ),
    ]
