# Generated by Django 5.1.7 on 2025-09-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_licensesratings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifications',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country of Institution'),
        ),
    ]
