# Generated by Django 5.2.5 on 2025-09-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_qualifications_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualifications',
            old_name='continuous_training_expiry',
            new_name='training_expiry',
        ),
        migrations.RenameField(
            model_name='qualifications',
            old_name='continuous_training_last_completed',
            new_name='training_last_completed',
        ),
        migrations.RemoveField(
            model_name='qualifications',
            name='aviation_certifications',
        ),
        migrations.RemoveField(
            model_name='qualifications',
            name='aviation_certifications_expiry',
        ),
        migrations.RemoveField(
            model_name='qualifications',
            name='certificate_upload',
        ),
        migrations.RemoveField(
            model_name='qualifications',
            name='continuous_training_records',
        ),
        migrations.RemoveField(
            model_name='qualifications',
            name='continuous_training_upload',
        ),
        migrations.RemoveField(
            model_name='qualifications',
            name='professional_development_courses',
        ),
        migrations.RemoveField(
            model_name='qualifications',
            name='professional_development_upload',
        ),
        migrations.RemoveField(
            model_name='qualifications',
            name='workshops_seminars',
        ),
        migrations.RemoveField(
            model_name='qualifications',
            name='workshops_upload',
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='reference_contact',
            field=models.CharField(blank=True, help_text='Reference person and contact (e.g. Chief Pilot – captain@airline.com)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='academic_certificates',
            field=models.FileField(blank=True, null=True, upload_to='documents/academic/', verbose_name='Academic Certificates'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='aviation_licenses',
            field=models.FileField(blank=True, null=True, upload_to='documents/licenses/', verbose_name='Aviation Licenses'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='cv_resume',
            field=models.FileField(blank=True, null=True, upload_to='documents/cv/', verbose_name='CV / Resume'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='employment_contracts',
            field=models.FileField(blank=True, null=True, upload_to='documents/contracts/', verbose_name='Employment Contracts'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='employment_references',
            field=models.FileField(blank=True, null=True, upload_to='documents/references/', verbose_name='Employment Reference Letters'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='License Expiry Date'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='logbooks',
            field=models.FileField(blank=True, null=True, upload_to='documents/logbooks/', verbose_name='Logbooks / Duty Records'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/medical/', verbose_name='Medical Certificate'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='medical_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Medical Certificate Expiry'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='memberships',
            field=models.FileField(blank=True, null=True, upload_to='documents/memberships/', verbose_name='Membership Certificates'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='national_id',
            field=models.FileField(blank=True, null=True, upload_to='documents/national_id/', verbose_name='National ID'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='passport_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/passport/', verbose_name='Passport Copy'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Expiry Date'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='professional_certifications',
            field=models.FileField(blank=True, null=True, upload_to='documents/professional_certifications/', verbose_name='Professional Certifications'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='professional_certifications_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Certifications Expiry Date'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='security_clearances',
            field=models.FileField(blank=True, null=True, upload_to='documents/security_clearances/', verbose_name='Security Clearances'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='training_records',
            field=models.FileField(blank=True, null=True, upload_to='documents/training/', verbose_name='Training Records'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='type_rating_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Type Rating Expiry'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='type_ratings_endorsements',
            field=models.FileField(blank=True, null=True, upload_to='documents/type_ratings/', verbose_name='Type Ratings & Endorsements'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='nature_of_employer',
            field=models.CharField(blank=True, choices=[('Airline', 'Airline'), ('Charter Operator', 'Charter Operator'), ('MRO', 'MRO'), ('Training', 'Training'), ('Military', 'Military'), ('School', 'School'), ('Ground Handling', 'Ground Handling'), ('ATC', 'ATC'), ('UAV Operator', 'UAV Operator'), ('Regulator', 'Regulator')], help_text='Select the nature of the employer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='types_of_aircraft',
            field=models.CharField(blank=True, choices=[('B737-800, A320, Dash 8', 'B737-800, A320, Dash 8'), ('Q400, Embraer 190, Cessna 208', 'Q400, Embraer 190, Cessna 208')], help_text='Types of aircraft flown/maintained', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='types_of_mission',
            field=models.CharField(blank=True, choices=[('Domestic', 'Domestic'), ('International', 'International'), ('Long Haul', 'Long Haul'), ('Short Haul', 'Short Haul'), ('Cargo', 'Cargo'), ('VIP', 'VIP'), ('Humanitarian', 'Humanitarian'), ('Military', 'Military')], help_text='Scope of operations / type of missions', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qualifications',
            name='expected_graduation_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Expected Graduation Year'),
        ),
        migrations.AlterField(
            model_name='qualifications',
            name='highest_education_level',
            field=models.CharField(choices=[('primary', 'Primary'), ('high_school', 'High School'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=20, verbose_name='Highest Education Level'),
        ),
    ]
