# Generated by Django 5.2.5 on 2025-09-04 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
        ('jobs_postings', '0004_jobposting_internal_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='job_applica_status_571256_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['created_at'], name='job_applica_created_5de96b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='job_applica_job_id_0efce7_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'created_at'], name='job_applica_applica_7a594b_idx'),
        ),
    ]
