# Generated by Django 5.2.5 on 2025-09-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0002_jobapplication_job_applica_status_571256_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='profile_score',
            field=models.FloatField(default=0),
        ),
    ]
