# Generated by Django 5.2.5 on 2025-08-19 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('aircraft_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qualifications', models.TextField()),
                ('experience_required', models.IntegerField(help_text='Experience required in years')),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('contract', 'Contract'), ('temporary', 'Temporary')], max_length=50)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('license_requirements', models.CharField(blank=True, max_length=255)),
                ('total_flying_hours_required', models.IntegerField(blank=True, null=True)),
                ('specific_aircraft_hours_required', models.IntegerField(blank=True, null=True)),
                ('medical_certification_required', models.CharField(blank=True, max_length=100)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
