# Generated by Django 5.2.5 on 2025-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_postings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='experience_required',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='application_url',
            field=models.URLField(blank=True, help_text='External URL for applications if applicable', null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='benefits',
            field=models.TextField(blank=True, help_text='Benefits offered with this position', null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='contact_email',
            field=models.EmailField(default='contact@company.com', help_text='Email for inquiries about this position', max_length=254),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='expected_start_date',
            field=models.DateField(blank=True, help_text='Expected start date for this position', null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='experience_level',
            field=models.CharField(choices=[('entry', '0-2 years: Entry Level'), ('mid', '3-5 years: Mid Level'), ('senior', '6-10 years: Senior Level'), ('executive', '10+ years: Executive Level')], default='entry', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_remote',
            field=models.BooleanField(default=False, help_text='Is this position remote?'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Mark as an urgent position to fill'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='responsibilities',
            field=models.TextField(default='Key responsibilities for this position', help_text='Key responsibilities for this position'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('verified', 'Verified Professionals Only'), ('private', 'Private - By invitation only')], default='public', max_length=20),
        ),
    ]
