# Generated by Django 5.2.5 on 2025-08-27 10:22

import apps.jobs_postings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_postings', '0002_remove_jobposting_experience_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.jobs_postings.models.job_attachment_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs_postings.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
