# Generated by Django 5.2.5 on 2025-09-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_postings', '0003_jobattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Optional notes visible only to admins', null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_license_types',
            field=models.JSONField(blank=True, default=list, help_text='List of required license types (multi-select)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_licenses',
            field=models.JSONField(blank=True, default=list, help_text='List of specific licenses required (multi-select)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='screening_question_types',
            field=models.CharField(blank=True, choices=[('yes_no', 'Yes/No Question'), ('upload_certs', 'Upload Certificates'), ('availability', 'Availability Check')], help_text='Type of screening question if applicable', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='screening_questions',
            field=models.JSONField(blank=True, default=list, help_text='Optional screening questions for applicants'),
        ),
    ]
