# Generated by Django 5.2.5 on 2025-09-21 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_postings', '0005_jobview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobView',
            new_name='JobTrack',
        ),
    ]
