name: Deploy to Winguport

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # Database secrets
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}

      # Django secret key & debug
      DJANGO_SECRET_KEY: django-insecure-drhml4lu21lfzc6%xa-liip$!zcbzif59*ox%k6s%c13=p_j_-
      DEBUG: ${{ secrets.DEBUG }}

      # Email settings
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}

      # VPS deployment
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

      # GHCR login
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image tag
        id: tag
        run: echo "TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push backend
        run: |
          docker build \
            --build-arg DB_HOST=${{ secrets.DB_HOST }} \
            --build-arg DB_NAME=${{ secrets.DB_NAME }} \
            --build-arg DB_USER=${{ secrets.DB_USER }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg DB_PORT=${{ secrets.DB_PORT }} \
            --build-arg DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} \
            --build-arg DEBUG=${{ secrets.DEBUG }} \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/winguport-backend:${{ steps.tag.outputs.TAG }} ./backend

          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/winguport-backend:${{ steps.tag.outputs.TAG }} ghcr.io/${{ secrets.GHCR_USERNAME }}/winguport-backend:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/winguport-backend:${{ steps.tag.outputs.TAG }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/winguport-backend:latest

      - name: Build and push frontend
        run: |
          docker build \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/winguport-frontend:${{ steps.tag.outputs.TAG }} ./frontend

          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/winguport-frontend:${{ steps.tag.outputs.TAG }} ghcr.io/${{ secrets.GHCR_USERNAME }}/winguport-frontend:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/winguport-frontend:${{ steps.tag.outputs.TAG }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/winguport-frontend:latest